version: '3.8'
services:
  node:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
  postgres:
    image: postgres
    env_file:
      - .env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/posgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres:
    name: pgdata