version: '3.8'

services:
  express-app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - docker.env
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/posgresql/data
    env_file:
      - docker.env

volumes:
  postgres:
    name: pgdata