version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres
    env_file:
      - .env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/posgresql/data

volumes:
  postgres:
    name: pgdata